In [1]:
import math
import numpy as np

In [2]:
S0 = 50  # Current stock price
K = 40   # Strike price
r = 0.08  # Risk-free interest rate (annualized)
T = 2    # Time to expiration (in years)
v = 0.2  # Volatility of the stock (annualized)

In [3]:
def binomial_tree(S0, K, r, T, v, steps=5):
    dt = T / steps
    u = math.exp(v * math.sqrt(dt))  # Up factor
    d = 1 / u                        # Down factor
    p = (math.exp(r * dt) - d) / (u - d)  # Risk-neutral probability        
    
    price = np.zeros((steps + 1, steps + 1))
    price[0, 0] = S0
    prob = np.zeros((steps + 1, steps + 1))
    prob[0, 0] = 1
    
    for col in range(1, steps + 1):
        for row in range(1, col + 1):
            price[row-1, col] = (price[row-1, col-1] * u)
            price[row, col] = (price[row-1, col-1] * d)
            
        # 從前一期每個節點，分別累加上漲與下跌路徑的機率
        for row in range(col):
            prob[row, col] += prob[row, col - 1] * p
            prob[row + 1, col] += prob[row, col - 1] * (1 - p)
            
    
    print(price)
    print(prob)
    
    expected_price = 0
    for row in range(steps + 1):
        if price[row, steps] > K:
            expected_price += ((price[row, steps]-K) * prob[row, steps])
            
    expected_price = expected_price * math.exp(-r * T)
    
    return expected_price

binomial_tree(S0, K, r, T, v, steps=5)

[[50.         56.74196792 64.39301846 73.07573175 82.92921653 94.11133887]
 [ 0.         44.05909932 50.         56.74196792 64.39301846 73.07573175]
 [ 0.          0.         38.82408466 44.05909932 50.         56.74196792]
 [ 0.          0.          0.         34.21108404 38.82408466 44.05909932]
 [ 0.          0.          0.          0.         30.14619099 34.21108404]
 [ 0.          0.          0.          0.          0.         26.56428046]]
[[1.         0.59661392 0.35594817 0.21236363 0.1266991  0.07559045]
 [0.         0.40338608 0.4813315  0.43075361 0.34265813 0.25554326]
 [0.         0.         0.16272033 0.29124364 0.34752002 0.3455588 ]
 [0.         0.         0.         0.06563912 0.15664484 0.23364123]
 [0.         0.         0.         0.         0.02647791 0.07898544]
 [0.         0.         0.         0.         0.         0.01068082]]


np.float64(16.4261691635653)